#:schema https://json.schemastore.org/air.json

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"

include_ext = ["go", "env"]

exclude_dir = [
  "tmp",
  "vendor",
  "testdata",
]

exclude_regex = [
  "_test.go",
]

delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true
keep_scroll = true